# Generated by Django 3.2.9 on 2021-12-23 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hood',
            name='emergency_line',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hood',
            name='police_line',
            field=models.CharField(max_length=10),
        ),
    ]
