# Generated by Django 3.2.9 on 2021-12-23 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood_app', '0002_auto_20211223_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hood_app.services'),
        ),
    ]
