# Generated by Django 3.2.9 on 2021-12-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood_app', '0003_auto_20211223_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
