# Generated by Django 3.2.9 on 2021-12-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood_app', '0005_alter_hood_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
