# Generated by Django 3.2.9 on 2021-12-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood_app', '0006_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurence',
            name='description',
        ),
        migrations.AlterField(
            model_name='occurence',
            name='name',
            field=models.CharField(max_length=3000),
        ),
    ]
