# Generated by Django 3.2.9 on 2022-01-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood_app', '0011_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
